#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=38
TOTAL_MINUTES=270

REPO="danielbaldwin47/resolve-mcp"
issue_url() { printf 'https://github.com/%s/issues/%s' "$REPO" "$1"; }

# Run everything from the repo root, whichever checkout this script lives in.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# run_test <ticket> <cmd...> — run a command, show pass/fail, never abort the
# wizard. A failure reminds you of the new-ticket protocol from #79.
run_test() {
  local ticket="$1"; shift
  printf '  %s$%s %s\n' "$BOLD" "$RESET" "$*"
  local rc=0
  "$@" || rc=$?
  if (( rc == 0 )); then
    printf '  %s✓ passed%s\n' "$GREEN" "$RESET"
  else
    printf '  %s✗ failed (exit %s)%s\n' "$RED" "$rc" "$RESET"
    warn "protocol: a failure becomes a new ticket linked back to #$ticket and #79"
  fi
  return 0
}

# record <ticket> — post the result comment on the source ticket (gh, with a
# browser fallback). #79 protocol: an unrecorded pass gets re-run.
record() {
  local ticket="$1" body="" line
  say "Record the result on #$ticket — pass/fail, hardware, interpreter, any output the item asks for."
  if [[ "${GH_OK:-0}" == "1" ]] && confirm "Post it to #$ticket via gh now?"; then
    say "Type the comment. End with a single '.' on its own line:"
    while IFS= read -r line; do
      [[ "$line" == "." ]] && break
      body+="$line"$'\n'
    done
    if [[ -n "$body" ]] && gh issue comment "$ticket" --repo "$REPO" --body "$body" >/dev/null 2>&1; then
      printf '  %s✓ recorded%s on #%s\n' "$GREEN" "$RESET" "$ticket"
    else
      SKIPPED+=("result comment on #$ticket")
      warn "couldn't post — record it on #$ticket by hand"
      open_url "$(issue_url "$ticket")"
      pause "Paste the result on #$ticket, then press Enter."
    fi
  else
    open_url "$(issue_url "$ticket")"
    pause "Paste the result on #$ticket, then press Enter."
  fi
  say "Now tick this item's box on the #79 tab."
}

# skip_done — Enter runs the item; y skips one already done and recorded.
skip_done() {
  if confirm "Skip this item (already done and recorded)?"; then
    note "skipped"
    return 1
  fi
  return 0
}

banner "Live verification pass — issue #79 at the Resolve box"

# ── Stage 1: preconditions ────────────────────────────────────────────────
stage "Preconditions" 5
say "One sitting clears every live AC, install and manual check from the P1 merge train."
step "Start Resolve Studio."
warn "Open a THROWAWAY or SNAPSHOTTED project (snapshot_project or the GUI) with a timeline — the tests mutate it."
note "The build tests leave 'resolve-mcp-smoke v<N>', 'resolve-mcp smoke …' and 'resolve-mcp-lock-probe' timelines; the last stage deletes them."
GH_OK=0
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  GH_OK=1
  say "gh is authenticated — the wizard can post result comments for you."
else
  warn "gh unavailable/unauthenticated — you'll paste result comments in the browser instead."
fi
command -v uv >/dev/null 2>&1 || warn "uv not on PATH — the pytest stages will fail until it is."
open_url "$(issue_url 79)"
say "Keep the #79 tab open — you tick each box there as its result lands on the source ticket."
if ! confirm "Resolve Studio running with a throwaway/snapshotted project and a timeline open?"; then
  warn "Set that up first, then re-run this wizard."
  exit 1
fi

# ── Section 1 — installs (once per machine) ───────────────────────────────

stage "Install — ffmpeg on PATH (#32)" 5
if skip_done; then
  run_test 32 ffmpeg -version
  say "If that failed: install ffmpeg, or set RESOLVE_MCP_FFMPEG to the exe's path."
  record 32
fi

stage "Install — transcription extra (#35)" 10
if skip_done; then
  run_test 35 uv sync --extra analysis
  note "The first transcription run downloads Whisper large-v3 (GB-scale — check disk space now)."
  say "Tick the box on #79 if it synced clean."
fi

stage "Install — audio-separator (#36)" 10
if skip_done; then
  say "audio-separator can live in its own env — install it however you like:"
  step "pip install \"audio-separator[gpu]\""
  note "First run downloads htdemucs_ft + MDX23C-DrumSep."
  pause "Install it (or confirm it's already installed), then press Enter."
  run_test 36 audio-separator --version
  say "If the exe isn't on PATH, set RESOLVE_MCP_AUDIO_SEPARATOR to its full path."
  say "Tick the box on #79 once the version answers."
fi

stage "Install — beat_this (#37)" 5
if skip_done; then
  run_test 37 uv pip install 'beat_this @ git+https://github.com/CPJKU/beat_this'
  step "Look at the install output above: did it pull a CUDA torch or a CPU torch?"
  say "That answer decides the optional-dependency-group question in the decisions stage."
  record 37
fi

# ── Section 2 — fixtures to prepare by hand ───────────────────────────────

stage "Fixture — markers timeline (#31)" 5
if skip_done; then
  step "In the GUI: make a timeline that starts at 01:00:00:00."
  step "Hand-place at least one marker on it."
  pause "Done? Press Enter (and tick the box on #79)."
fi

stage "Fixture — media pool: a still and a long clip (#28/#29/#62-3)" 5
if skip_done; then
  step "Import one PNG or JPG into the media pool."
  step "Import a clip of at least 200 frames that has a frame rate; keep one copy in the ROOT folder."
  pause "Done? Press Enter (and tick both boxes on #79)."
fi

stage "Fixture — Text+ template .drb (#41/#42)" 15
if skip_done; then
  step "In the GUI: author a Text+ title."
  step "Put it in a bin ON ITS OWN."
  step "Right-click the bin → Export Bin → save the .drb somewhere you'll remember."
  note "No API exists for this step."
  step "Then import that .drb back into the media pool by hand — #42 needs the pool clip."
  pause "Done? Press Enter (and tick the box on #79)."
fi

# ── Section 3 — fast tests: open project/timeline only ────────────────────

stage "Markers read-back (#31)" 3
if skip_done; then
  run_test 31 uv run pytest -m live -k markers -s
  step "Eye-compare the printed table against the markers in the GUI."
  record 31
fi

stage "Interchange formats write (#26)" 2
if skip_done; then
  note "Read-only test."
  run_test 26 uv run pytest -m live -k interchange_formats
  record 26
fi

stage "OTIO round-trip (#26)" 3
if skip_done; then
  run_test 26 uv run pytest -m live -k otio_round_trip
  record 26
fi

stage "Hand-injected dissolve (#26)" 5
if skip_done; then
  run_test 26 uv run pytest -m live -k dissolve
  step "Open the imported 'resolve-mcp smoke dissolve …' timeline in the GUI."
  step "Confirm the dissolve AND the fade-to-black by eye."
  warn "Transitions have no scripting getter — the green test alone is half the AC. Record BOTH halves."
  record 26
fi

stage "EXPORT_FCPXML_1_12 probe (#26)" 3
if skip_done; then
  step "In run_python or a console: check dir(resolve) for EXPORT_FCPXML_1_12 or higher."
  say "If present: a one-line ladder bump is due in src/resolve_mcp/resolve/interchange.py — note it on #26."
  record 26
fi

stage "Build places every shot (#28)" 3
if skip_done; then
  note "Re-run needed for #29/#30's changed 'placed' shape."
  run_test 28 uv run pytest -m live -k real_build_places
  record 28
fi

stage "Take selector swap (#29)" 3
if skip_done; then
  say "Settles AddTake's half-open endFrame, post-AddTake selection state, and that the swap really plays alternate frames."
  run_test 29 uv run pytest -m live -k take_selector
  record 29
fi

stage "Rebuild versions (#28)" 3
if skip_done; then
  run_test 28 uv run pytest -m live -k rebuild_makes_the_next_version
  record 28
fi

stage "Still duration honoured (#28, clears #62 item 3)" 3
if skip_done; then
  run_test 28 uv run pytest -m live -k still_lands
  record 28
fi

stage "Locked-track footgun (#28)" 3
if skip_done; then
  run_test 28 uv run pytest -m live -k locked_track_footgun
  record 28
fi

stage "Invalid cut builds nothing (#28)" 2
if skip_done; then
  run_test 28 uv run pytest -m live -k invalid_cut_creates_no
  record 28
fi

stage "Frame grab lands on the numbered moment (#34)" 3
if skip_done; then
  run_test 34 uv run pytest -m live -k real_frame_grab
  record 34
fi

stage "Preset list (#33 → also #71)" 3
if skip_done; then
  run_test 33 uv run pytest -m live -k preset_list -s
  step "Paste the printed preset names on BOTH #33 and #71 — #46 is blocked on that catalog."
  record 33
  record 71
fi

stage "Takes read-back on inspect_timeline (#68)" 3
if skip_done; then
  say "With the selector timeline from the swap test still present:"
  step "Run inspect_timeline and confirm it reports non-zero 'takes' on the swapped clip."
  record 68
fi

# ── Section 4 — tests with their own setup ────────────────────────────────

stage "Text+ .drb round-trip (#41)" 10
if skip_done; then
  warn "Run this BEFORE apply_titles — a shared-comp finding here invalidates #42's route."
  warn "Mutates then cleans a scratch bin/timeline — throwaway project first."
  ask TEXTPLUS_DRB "Full path to the .drb you exported earlier:"
  run_test 41 env RESOLVE_MCP_TEXTPLUS_TEMPLATE="$TEXTPLUS_DRB" uv run pytest -m live -s -k text_plus
  step "Paste the FULL printed report on #41 — a failure is the more valuable finding."
  record 41
fi

stage "apply_titles end-to-end (#42)" 10
if skip_done; then
  say "Needs the template already imported into the media pool (fixture stage)."
  ask TITLES_POOL_CLIP "Pool clip name of the imported template:"
  run_test 42 env RESOLVE_MCP_TITLES_TEMPLATE="$TITLES_POOL_CLIP" uv run pytest -m live -s -k apply_titles
  warn "The Opacity1 fade keyframing is the step no seam covers — paste the printed report on #42."
  record 42
fi

stage "Whisper word shape (#35)" 15
if skip_done; then
  note "First run downloads the model (GB-scale); GPU makes it quick."
  run_test 35 uv run pytest -m live -k faster_whisper
  record 35
fi

stage "Beat model hears a click track (#37)" 5
if skip_done; then
  note "Lives in tests/test_live_analysis.py."
  run_test 37 uv run pytest -m live -k beat_model
  record 37
fi

# ── Section 5 — slow tests: start these and walk away ─────────────────────

stage "Timeline mix export (#32) — slow" 30
if skip_done; then
  warn "Full-timeline audio render, up to 30 min timeout. Start it and walk away."
  run_test 32 uv run pytest -m live -k render_queue_exports
  say "If it failed: the fix lands in audio/acquire.py:export_timeline_mix."
  record 32
fi

stage "Range render covers its frames (#33) — 'the dangerous one'" 15
if skip_done; then
  say "Needs a timeline of at least 13 s open. Renders twice."
  if confirm "Use a specific render preset (RESOLVE_MCP_RENDER_PRESET)?"; then
    ask RENDER_PRESET "Preset name:"
    run_test 33 env RESOLVE_MCP_RENDER_PRESET="$RENDER_PRESET" uv run pytest -m live -k range_render
  else
    run_test 33 uv run pytest -m live -k range_render
  fi
  warn "Until this passes, range renders are unverified."
  record 33
fi

stage "Scene scan on the clip's own clock (#34) — slow" 10
if skip_done; then
  note "Decodes the shortest pool clip in full."
  run_test 34 uv run pytest -m live -k real_scene_scan
  record 34
fi

stage "Two-pass stem separation (#36) — slow, watch the GPU" 20
if skip_done; then
  warn "Open Task Manager and WATCH GPU usage while it runs — no seam can assert the device, and a CPU torch turns minutes into hours silently."
  run_test 36 uv run pytest -m live -k real_separator
  step "Record pass/fail AND the device observation (GPU or CPU) on #36."
  record 36
fi

# ── Section 6 — manual checks, no test file ───────────────────────────────

stage "#62-1 — open_project reflects in get_status" 3
if skip_done; then
  step "Call open_project against a real project."
  step "Does get_status reflect it immediately?"
  record 62
fi

stage "#62-2 — PNG image-sequence import" 5
if skip_done; then
  step "Import a PNG image sequence via import_media."
  step "Record WHAT RESOLVE NAMES THE CLIP on #62."
  record 62
fi

stage "#62-4 — relink_media, both routes" 8
if skip_done; then
  say "Against genuinely offline media:"
  step "Folder route: RelinkClips."
  step "Moved-and-renamed route: ReplaceClip."
  record 62
fi

stage "#62-5 — 'Audio Ch' property key in the session log" 5
if skip_done; then
  say "After any live run with clips, grep the session log for the 'Audio Ch' property key (#27)."
  note "Logging is stderr-only (src/resolve_mcp/logging_config.py) — the 'session log' is wherever your MCP client captured the server's stderr."
  warn "A different spelling means E7 silently passes everything."
  record 62
fi

stage "Marker write (#31)" 3
if skip_done; then
  step "Call set_markers([{\"frame\": <inside timeline>, \"color\": \"Blue\", \"name\": \"test\", \"note\": \"delete me\"}])."
  step "Confirm the marker in the GUI, then delete it."
  record 31
fi

stage "Optional items (#25, #35)" 5
if confirm "Run the optional items too?"; then
  say "Timeline-tail exclusivity (#25):"
  step "Re-run the frame-math test against a timeline with media in its last 600 frames."
  say "Silence defaults (#35):"
  step "Transcribe a real concert mix; sanity-check the −40 dB / 0.35 s silence spans."
  pause "Record anything you ran on its ticket, then press Enter."
else
  note "skipped — they stay unticked on #79"
fi

# ── Section 7 — decisions queued on you ───────────────────────────────────

stage "Decisions queued on you" 15
say "Answer each on the named ticket (open them from the #79 tab):"
step "#57 — bin-layout conventions: house layout or explicitly neutral (asked three times on #24; #44/#47 want it)."
step "#71 — render preset catalog: house or neutral, where it lives, preset-per-song in the cut file, missing-preset behaviour. #46 IS BLOCKED ON THIS."
step "#27 — confirm the E5-stills deviation (dry-run validation never writes the still Out workaround)."
step "#34 — confirm fingerprint-not-hash cache reading, or ask for content-hashing on the frame/scene routes."
step "#37 — should beat_this become a real optional-dependency group in pyproject? (Also answers #38–#40; use the CUDA-torch answer from the install stage.)"
step "#42 — (a) keep or fold the three-tool catalog amendment (get_titles_schema/validate_titles vs #14 §7); if kept, #12 and #14 want a line each. (b) confirm marker-relative event offsets."
step "#68 — schedule the remaining getter-sweep + its live AC (the rename shipped in PR #74)."
step "#42's surfaced gaps — which become tickets: automating .drb import; list_title_templates (fits #43); a songs.json owner; markers-on-rebuild needing hand re-marking."
pause "Answer them now or defer — tick the ones you answered on #79, then press Enter."

# ── Section 8 — wrap up ───────────────────────────────────────────────────

stage "Wrap up" 10
step "Delete every 'resolve-mcp-smoke v<N>' / 'resolve-mcp smoke …' / 'resolve-mcp-lock-probe' timeline and any scratch bins."
step "Confirm every ticked item on #79 has its result comment on the source ticket — an unrecorded pass gets re-run."
open_url "$(issue_url 79)"
pause "All boxes ticked and recorded? Press Enter to finish."

finish
